### ISSUE TITLE
Error when specifying place ID.

### ISSUE THREAD

**Issue by SQL-enwiki** [rainbow-sh/Wfetch#10]
From #1 it seems like we can specify place ID's like so:

`wfetch --place=4674006`

Doing so results in an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/wfetch", line 127, in <module>
    Fire(main) # Launch main function with arguments
    ^^^^^^^^^^
  File "/home/sql/.local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sql/.local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/sql/.local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wfetch", line 87, in main
    INFO = f'''    \u001b[1m\u001b[{COLOR}m{WEATHER.detailed_status.title().replace(" ", "")}\u001b[37m@{CITY.split(', ')[0]}\u001b[0m
                                                                                                         ^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
```

**Comment by Gcat101** [comment]
Wow somebody still uses this? I wrote it 1.5 years ago (mostly for myself) and I don't remember all of the details. I will try to fix this though.

**Comment by Gcat101** [comment]
Was able to replicate.

**Comment by Gcat101** [comment]
Fixed
